export default {
  COLOR: {
    BLACK: '#000',
    BLUE: '#1826cc',
    DARKGREY: '#7c7c7c',
    DARKGREY2: '#999999',
    DARKGREEN: '#22B335',
    GREY: '#bfbfbf',
    LIGHTBLUE: '#3AABE0',
    LIGHTGREY: '#d3d3d3',
    LIGHTGREY2: '#e8e7e3',
    LIGHTGREEN: '#85e28a',
    ORANGE: '#FC862D',
    WHITE: '#fff',
    YELLOW: '#f2d832',
  },
  ZERO: '0',
  ICONSIZE: 25,
  ICONSIZEBIG: 120,
  STORAGE_KEYS: {
    userId: 'userId',
    userType: 'userType',
    userLatitude: 'userLatitude',
    userLongitude: 'userLongitude',
  },
};
